### PR TITLE
UI Changes/ Peak Force Calculation Adjustment

### PR DESCRIPTION
**Pull request by aferguson3**
### Main Changes
* Defined a style for all activities and buttons
* Upgraded gradle version to 7.2.0 and SDK version to 32 (to comply with styling libraries used)
* Fixed charts being visible with invalid criteria on all time stats page
* Adjusted the peak force calculation

studio64_lBhVTATE7i

### CODE REVIEW

**Comment by colefisher1** [comment]
Some UI nitpicks for future reference: 

**Navbar**
- I think the navbar should slightly differ in color from the normal background, like what was demoed in our last meeting.
- The way the navbar highlights with the purple pills isn't really ideal, in my opinion, because it makes the icon squares visible.

**Buttons**
- Button color across activities should be consistent. It seems that some are pink and others are blue.

**Page Headers**
- Page Headers should be a consistent font, font size, and centered on each page

**Charts**
- It seems that you've been able to modify chart background color. In my opinion, we should make the chart background color a slightly lighter shade of grey (than the background color), as well as make the axis labels white instead of black.

**Comment by colefisher1** [comment]
Regarding Gradle, I am getting the following error on my end: 
 `This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2021.2.1 or newer.`

This most likely means I need to reinstall Android Studio. It would also likely require that I modify gradle/wrapper/gradle-wrapper.properties to account for the new gradle version. @micahbow Could you test on your end? It may not make sense to go with this new Gradle version if it is going to cause issues on multiple computers.

**Comment by aferguson3** [comment]
Based on the styles I defined, the background color and text color gets changed throughout all activities, unless it's already defined in the activities' xml files. I didn't rework the whole UI and is Tim working on the navbar. I suggest a new collaborative branch for the UI to better reflect the UI changes. This would address the issues with the navbar and the buttons. 

I'll work on standardizing the font size for the header and adjusting the background for the charts, but I'm unsure on how to update colors for the axis labels.

**Comment by colefisher1** [comment]
A collaborative UI branch sounds like a great idea. I will look into the axis labels and get back to you.

**Comment by aferguson3** [comment]
Sounds good

**Comment by aferguson3** [comment]
Oh and regarding your gradle version comment, are you able to update your gradle version in Android Studio?

**Comment by colefisher1** [comment]
When I pull in your code, I get the error above. Could you share a photo of your distribution url in gradle/wrapper/gradle-wrapper.properties?

**Comment by aferguson3** [comment]
image

**Comment by colefisher1** [comment]
I was able to update my Android Studio and get it to work with Gradle 7.2, thanks for your help. One small thing I noticed was that the theme was being applied to the toast popups in AddExerciseActivity, which we will need to fix.

image

**Comment by aferguson3** [comment]
That’s new to me I’ve never seen this issue. I’ll investigate it.

**Comment by colefisher1** [comment]
For documentation purposes, restating here that Antoine and I believe the issue to be due to incompatibility of the material 3 theme for my older emulated device (Nexus 4 API 27). We will need to test the UI on the demo device to see if the issue exists there.

[Edit]: After doing some research, however, I have yet to find any info justifying that material3 is incompatible with old devices.

**Comment by micahbow** [comment]
Just ran it on the device, still seeing some graphical issues:
image

**Pull request closed without merging**
